### ISSUE TITLE
Current release `0.1.2` does not have patched lockfile

### ISSUE THREAD

**Issue by nickgerace** [buildkite/test-collector-rust#34]
## Description

The current release (`0.1.2`) does not contain the fix from #7. This prevents users from using a frozen lockfile to build the collector.

## Reproduction

You can reproduce the issue by executing the following:

```shell
git checkout 0.1.2
cargo build --frozen --release
```

**Comment by jimsynz** [comment]
I don't have permission to release this crate anymore - @gchan or @KatieWright26; any chance you can cut a new release?

**Comment by pda** [comment]
I can sort that out! 👍🏼

I imagine we'll need to bump the patch-level to v0.1.3 as presumably we can't amend the [existing v0.1.2 release](https://crates.io/crates/buildkite-test-collector/0.1.2)?

**Comment by nickgerace** [comment]
I believe that is correct @pda. You could also yank `0.1.2`, but I don't know that it's necessary since it builds for everyday users (`cargo install`). Thank you!

**Comment by pda** [comment]
I believe this is sorted in https://crates.io/crates/buildkite-test-collector/0.1.3
(Hopefully I haven't made the same/similar mistake 😅)
As far as I can tell, I can `cargo build --frozen --release` the v0.1.3 tag.

**Comment by nickgerace** [comment]
Thank you all! I think that works well :)

**Comment by nickgerace** [comment]
Are you going to `git tag` for version `0.1.3`. @pda?

**Comment by pda** [comment]
Oops, I didn't see your reply.

I believe I did create the [git tag v0.1.3](https://github.com/buildkite/test-collector-rust/releases/tag/v0.1.3):

<img width="457" alt="image" src="https://github.com/user-attachments/assets/7bf4309b-618e-4d53-a473-b81e60399571">


But perhaps I should have also drafted/publishes a Release for that tag?

I've done that now:
https://github.com/buildkite/test-collector-rust/releases/tag/v0.1.3

**Comment by nickgerace** [comment]
Thank you!
